name: Publish Docker image
on:
  release:
    types: [published]
jobs:
  push_to_registry:
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    env:
      GITHUB_SHORT_SHA: ${GITHUB_SHA::8}
      GITHUB_REF_NAME: ${GITHUB_REF##*/}
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build container image
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/prometheus-ecr-exporter:${GITHUB_SHORT_SHA}
            ghcr.io/${{ github.repository_owner }}/prometheus-ecr-exporter:${GITHUB_REF_NAME}